[variables]
NODE_ENV = "production"
PLAYWRIGHT_HEADLESS = "true"

[phases.setup]
nixPkgs = ["nodejs_20", "playwright", "chromium"]

[phases.install]
cmds = [
  "npm ci",
  "npx playwright install --with-deps chromium"
]

[phases.build]
cmds = [
  "npm run build"
]

[start]
cmd = "npm run start"
